CvBundle\Entity\Experience:
    type: entity
    table: null
    repositoryClass: CvBundle\Repository\ExperienceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        description:
            type: text
        dateDebut:
            type: date
            column: date_debut
        dateFin:
            type: date
            column: date_fin
    lifecycleCallbacks: {  }
